- name: Set data dir permissions
  ansible.builtin.file:
    dest: "{{ redpanda_base_dir }}"
    src: "{{ repdanda_mount_dir }}"
    state: link
    owner: root
    group: root
    mode: "0775"
  tags:
    - data_dir_perms
