- name: Query GCE for VM instances in multiple zones
  google.cloud.gcp_compute_instance_info:
    zone: "{{ item }}"
    filters:
      - "(labels.role = client) AND (status = RUNNING OR status = PENDING)"
    project: "{{ gcp_project_id }}" 
    auth_kind: machineaccount
    service_account_email: "{{ gcp_service_account }}"
  loop:
    - "asia-south1-a"
    - "asia-south1-b"  # Add your additional zones here
    - "asia-south1-c"
  register: gce_redpanda_brokers
        
- name: Print VM instance data from all zones
  ansible.builtin.debug:
    msg: "gce_redpanda_brokers: {{ gce_redpanda_brokers }}" 

- name: Set fact for VM instance IP addresses
  set_fact:
    vm_instance_ips: "{{ gce_redpanda_brokers.results | map(attribute='resources') | flatten | json_query('[].networkInterfaces[0].networkIP') }}"

- name: Print the IP addresses fact
  debug:
    msg: "IP Address Of Redpanda Broker {{ vm_instance_ips }}"