---
redpanda_base_dir: /var/lib/redpanda
repdanda_mount_dir: /mnt/vectorized/redpanda
redpanda_truststore_file: "{{ redpanda_certs_dir }}/truststore.pem"
redpanda_cert_file: "{{ redpanda_certs_dir }}/node.crt"
debian_prerequisite_packages:
  - debian-keyring
  - debian-archive-keyring
  - apt-transport-https
  - ca-certificates
  - gnupg
  - iotop
  - mdadm
  - xfsprogs
  - openssl
rpm_prerequisite_packages:
  - curl
  - yum-utils
  - dnf-plugins-core
  - openssl
redpanda_certs_dir: /etc/redpanda/certs
